; Рекомендуемые значения для Zonefall Protocol (можно переопределить в DefaultEngine.ini проекта).
[ConsoleVariables]
r.FidelityFX.FSR.Enabled=1
r.FidelityFX.FI.Enabled=0
r.FidelityFX.FI.OverrideSwapChainDX12=0
r.FidelityFX.FI.AllowAsyncWorkloads=0
